#!/usr/bin/env bash
#
# This file is generated by l2tdevtools update-dependencies.py any dependency
# related changes should be made in dependencies.ini.

# Exit on error.
set -e

# Dependencies for running plaso, alphabetized, one per line.
# This should not include packages only required for testing or development.
PYTHON3_DEPENDENCIES="libbde-python3
                      libesedb-python3
                      libevt-python3
                      libevtx-python3
                      libewf-python3
                      libfsntfs-python3
                      libfvde-python3
                      libfwnt-python3
                      libfwsi-python3
                      liblnk-python3
                      libmsiecf-python3
                      libolecf-python3
                      libqcow-python3
                      libregf-python3
                      libscca-python3
                      libsigscan-python3
                      libsmdev-python3
                      libsmraw-python3
                      libvhdi-python3
                      libvmdk-python3
                      libvshadow-python3
                      libvslvm-python3
                      python3-artifacts
                      python3-bencode
                      python3-biplist
                      python3-certifi
                      python3-chardet
                      python3-construct
                      python3-crypto
                      python3-dateutil
                      python3-dfdatetime
                      python3-dfvfs
                      python3-dfwinreg
                      python3-dtfabric
                      python3-efilter
                      python3-elasticsearch
                      python3-elasticsearch5
                      python3-future
                      python3-idna
                      python3-lz4
                      python3-pefile
                      python3-psutil
                      python3-pyparsing
                      python3-pytsk3
                      python3-requests
                      python3-six
                      python3-tz
                      python3-urllib3
                      python3-xlsxwriter
                      python3-yaml
                      python3-yara
                      python3-zmq";

# Additional dependencies for running plaso tests, alphabetized,
# one per line.
TEST_DEPENDENCIES="python-mock";

# Additional dependencies for doing plaso development, alphabetized,
# one per line.
DEVELOPMENT_DEPENDENCIES="python-sphinx
                          pylint";

sudo add-apt-repository ppa:gift/dev -y
sudo apt-get update -q
sudo apt-get install -y ${PYTHON3_DEPENDENCIES}

if [[ "$*" =~ "include-development" ]]; then
    sudo apt-get install -y ${DEVELOPMENT_DEPENDENCIES}
fi

if [[ "$*" =~ "include-test" ]]; then
    sudo apt-get install -y ${TEST_DEPENDENCIES}
fi
