#!/usr/bin/env bash
set -e
sudo add-apt-repository ppa:gift/dev -y
sudo apt-get update -q
sudo apt-get install -y ipython \
                        libbde-python \
                        libesedb-python \
                        libevt-python \
                        libevtx-python \
                        libewf-python \
                        libfwsi-python \
                        liblnk-python \
                        libmsiecf-python \
                        libolecf-python \
                        libqcow-python \
                        libregf-python \
                        libscca-python \
                        libsigscan-python \
                        libsmdev-python \
                        libsmraw-python \
                        libvhdi-python \
                        libvmdk-python \
                        libvshadow-python \
                        python-artifacts \
                        python-bencode \
                        python-binplist \
                        python-construct \
                        python-coverage \
                        python-coveralls \
                        python-dateutil \
                        python-dfvfs \
                        python-dfwinreg \
                        python-docopt \
                        python-dpkt \
                        python-hachoir-core \
                        python-hachoir-metadata \
                        python-hachoir-parser \
                        python-mock \
                        python-pefile \
                        python-protobuf \
                        python-psutil \
                        python-pyparsing \
                        python-pytsk3 \
                        python-requests \
                        python-six \
                        python-xlsxwriter \
                        python-yaml \
                        python-tz \
                        python-zmq