[tox]
envlist = py3{10,11,12,13,14},black,coverage,docformatter,docs,pylint,wheel,yamllint

[testenv]
allowlist_externals = ./run_tests.py
pip_pre = True
passenv =
  CFLAGS
  CPPFLAGS
  LDFLAGS
setenv =
  PYTHONPATH = {toxinidir}
deps =
  coverage: coverage
  wheel:
    build
    setuptools >= 65
    wheel
commands =
  py3{10,11,12,13,14}: ./run_tests.py
  coverage: coverage erase
  coverage: coverage run --source=plaso --omit="*_test*,*__init__*,*test_lib*" run_tests.py
  coverage: coverage xml
  wheel: python -m build --no-isolation --wheel

[testenv:black]
skipsdist = True
pip_pre = True
passenv =
  CFLAGS
  CPPFLAGS
  LDFLAGS
setenv =
  PYTHONPATH = {toxinidir}
deps =
  black
  setuptools >= 65
commands =
  black --version
  black .

[testenv:docformatter]
skipsdist = True
pip_pre = True
passenv =
  CFLAGS
  CPPFLAGS
  LDFLAGS
setenv =
  PYTHONPATH = {toxinidir}
deps =
  docformatter
  setuptools >= 65
commands =
  docformatter --version
  docformatter --in-place --recursive plaso tests

[testenv:docs]
usedevelop = True
deps =
  -rdocs/requirements.txt
commands =
  sphinx-build -b html -d build/doctrees docs dist/docs
  sphinx-build -b linkcheck docs dist/docs

[testenv:pylint]
skipsdist = True
pip_pre = True
passenv =
  CFLAGS
  CPPFLAGS
  LDFLAGS
setenv =
  PYTHONPATH = {toxinidir}
deps =
  pylint >= 3.3.0, < 3.4.0
  setuptools >= 65
commands =
  pylint --version
  pylint --rcfile=.pylintrc plaso tests

[testenv:yamllint]
skipsdist = True
pip_pre = True
passenv =
  CFLAGS
  CPPFLAGS
  LDFLAGS
setenv =
  PYTHONPATH = {toxinidir}
deps =
  setuptools >= 65
  yamllint >= 1.26.0
commands =
  yamllint -v
  yamllint -c .yamllint.yaml plaso test_data
