#!/usr/bin/python
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import plaso.proto.transmission_pb2

DESCRIPTOR = descriptor.FileDescriptor(
  name='plaso/proto/plaso_storage.proto',
  package='plaso_storage',
  serialized_pb='\n\x1fplaso/proto/plaso_storage.proto\x12\rplaso_storage\x1a\x1eplaso/proto/transmission.proto\"\'\n\tAttribute\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\xfc\x03\n\x0b\x45ventObject\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x16\n\x0etimestamp_desc\x18\x02 \x01(\t\x12<\n\x0csource_short\x18\x03 \x02(\x0e\x32&.plaso_storage.EventObject.SourceShort\x12\x13\n\x0bsource_long\x18\x04 \x02(\t\x12\x18\n\x10\x64\x65scription_long\x18\x05 \x02(\t\x12\x19\n\x11\x64\x65scription_short\x18\x06 \x02(\t\x12,\n\nattributes\x18\x08 \x03(\x0b\x32\x18.plaso_storage.Attribute\x12\x10\n\x08timezone\x18\t \x01(\t\x12\x10\n\x08\x66ilename\x18\n \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x0b \x01(\t\x12(\n\x08pathspec\x18\x0c \x01(\x0b\x32\x16.transmission.PathSpec\x12\x0e\n\x06offset\x18\r \x01(\x03\"\x97\x01\n\x0bSourceShort\x12\x06\n\x02\x41V\x10\x01\x12\x08\n\x04\x42\x41\x43K\x10\x02\x12\x07\n\x03\x45VT\x10\x03\x12\x08\n\x04\x45XIF\x10\x04\x12\x08\n\x04\x46ILE\x10\x05\x12\x07\n\x03LOG\x10\x06\x12\x07\n\x03LNK\x10\x07\x12\x07\n\x03LSO\x10\x08\x12\x08\n\x04META\x10\t\x12\t\n\x05PLIST\x10\n\x12\x07\n\x03RAM\x10\x0b\x12\n\n\x06RECBIN\x10\x0c\x12\x07\n\x03REG\x10\r\x12\x0b\n\x07WEBHIST\x10\x0e\"\xc4\x01\n\x0e\x45ventContainer\x12\x12\n\nfirst_time\x18\x01 \x02(\x03\x12\x11\n\tlast_time\x18\x02 \x02(\x03\x12\x31\n\ncontainers\x18\x04 \x03(\x0b\x32\x1d.plaso_storage.EventContainer\x12*\n\x06\x65vents\x18\x06 \x03(\x0b\x32\x1a.plaso_storage.EventObject\x12,\n\nattributes\x18\x08 \x03(\x0b\x32\x18.plaso_storage.Attribute')



_EVENTOBJECT_SOURCESHORT = descriptor.EnumDescriptor(
  name='SourceShort',
  full_name='plaso_storage.EventObject.SourceShort',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='AV', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BACK', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EVT', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='EXIF', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FILE', index=4, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LOG', index=5, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LNK', index=6, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LSO', index=7, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='META', index=8, number=9,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PLIST', index=9, number=10,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RAM', index=10, number=11,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RECBIN', index=11, number=12,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REG', index=12, number=13,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='WEBHIST', index=13, number=14,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=481,
  serialized_end=632,
)


_ATTRIBUTE = descriptor.Descriptor(
  name='Attribute',
  full_name='plaso_storage.Attribute',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='key', full_name='plaso_storage.Attribute.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='value', full_name='plaso_storage.Attribute.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=82,
  serialized_end=121,
)


_EVENTOBJECT = descriptor.Descriptor(
  name='EventObject',
  full_name='plaso_storage.EventObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='timestamp', full_name='plaso_storage.EventObject.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestamp_desc', full_name='plaso_storage.EventObject.timestamp_desc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='source_short', full_name='plaso_storage.EventObject.source_short', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='source_long', full_name='plaso_storage.EventObject.source_long', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='description_long', full_name='plaso_storage.EventObject.description_long', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='description_short', full_name='plaso_storage.EventObject.description_short', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='attributes', full_name='plaso_storage.EventObject.attributes', index=6,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timezone', full_name='plaso_storage.EventObject.timezone', index=7,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='filename', full_name='plaso_storage.EventObject.filename', index=8,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='display_name', full_name='plaso_storage.EventObject.display_name', index=9,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='pathspec', full_name='plaso_storage.EventObject.pathspec', index=10,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='offset', full_name='plaso_storage.EventObject.offset', index=11,
      number=13, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EVENTOBJECT_SOURCESHORT,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=124,
  serialized_end=632,
)


_EVENTCONTAINER = descriptor.Descriptor(
  name='EventContainer',
  full_name='plaso_storage.EventContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='first_time', full_name='plaso_storage.EventContainer.first_time', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='last_time', full_name='plaso_storage.EventContainer.last_time', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='containers', full_name='plaso_storage.EventContainer.containers', index=2,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='events', full_name='plaso_storage.EventContainer.events', index=3,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='attributes', full_name='plaso_storage.EventContainer.attributes', index=4,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=635,
  serialized_end=831,
)

_EVENTOBJECT.fields_by_name['source_short'].enum_type = _EVENTOBJECT_SOURCESHORT
_EVENTOBJECT.fields_by_name['attributes'].message_type = _ATTRIBUTE
_EVENTOBJECT.fields_by_name['pathspec'].message_type = plaso.proto.transmission_pb2._PATHSPEC
_EVENTOBJECT_SOURCESHORT.containing_type = _EVENTOBJECT;
_EVENTCONTAINER.fields_by_name['containers'].message_type = _EVENTCONTAINER
_EVENTCONTAINER.fields_by_name['events'].message_type = _EVENTOBJECT
_EVENTCONTAINER.fields_by_name['attributes'].message_type = _ATTRIBUTE
DESCRIPTOR.message_types_by_name['Attribute'] = _ATTRIBUTE
DESCRIPTOR.message_types_by_name['EventObject'] = _EVENTOBJECT
DESCRIPTOR.message_types_by_name['EventContainer'] = _EVENTCONTAINER

class Attribute(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ATTRIBUTE
  
  # @@protoc_insertion_point(class_scope:plaso_storage.Attribute)

class EventObject(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EVENTOBJECT
  
  # @@protoc_insertion_point(class_scope:plaso_storage.EventObject)

class EventContainer(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EVENTCONTAINER
  
  # @@protoc_insertion_point(class_scope:plaso_storage.EventContainer)

# @@protoc_insertion_point(module_scope)
