# -*- coding: utf-8 -*-
"""The Windows Registry definitions."""


# The Registry (file) types.
REGISTRY_FILE_TYPE_NTUSER = u'NTUSER'
REGISTRY_FILE_TYPE_SAM = u'SAM'
REGISTRY_FILE_TYPE_SECURITY = u'SECURITY'
REGISTRY_FILE_TYPE_SOFTWARE = u'SOFTWARE'
REGISTRY_FILE_TYPE_SYSTEM = u'SYSTEM'
REGISTRY_FILE_TYPE_UNKNOWN = u'UNKNOWN'
REGISTRY_FILE_TYPE_USRCLASS = u'USRCLASS'

REGISTRY_FILE_TYPES = frozenset([
    REGISTRY_FILE_TYPE_NTUSER,
    REGISTRY_FILE_TYPE_SAM,
    REGISTRY_FILE_TYPE_SECURITY,
    REGISTRY_FILE_TYPE_SOFTWARE,
    REGISTRY_FILE_TYPE_SYSTEM,
    REGISTRY_FILE_TYPE_USRCLASS])

# The Registry value types.
REG_NONE = 0
REG_SZ = 1
REG_EXPAND_SZ = 2
REG_BINARY = 3
REG_DWORD = 4
REG_DWORD_LITTLE_ENDIAN = 4
REG_DWORD_BIG_ENDIAN = 5
REG_LINK = 6
REG_MULTI_SZ = 7
REG_RESOURCE_LIST = 8
REG_FULL_RESOURCE_DESCRIPTOR = 9
REG_RESOURCE_REQUIREMENT_LIST = 10
REG_QWORD = 11
