# Run tests on Mac OS.
name: test_macos
on: [pull_request, push]
permissions: read-all
jobs:
  test_macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: macos-26
          python-version: '3.14'
          toxenv: 'py314'
    steps:
    - uses: actions/checkout@v6
    - name: Install dependencies
      run: |
        brew update -q
        brew install -q gettext gnu-sed openssl@3 python@${{ matrix.python-version }} tox || true
        brew link --force gettext
        echo "LDFLAGS=-L$(brew --prefix openssl@3)/lib" >> $GITHUB_ENV
        echo "CPPFLAGS=-I$(brew --prefix openssl@3)/include" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=$(brew --prefix openssl@3)/lib/pkgconfig" >> $GITHUB_ENV
    - name: Run tests
      run: |
        tox -e ${{ matrix.toxenv }}
