# Run tests on Windows.
name: test_windows
on: [push, pull_request]
permissions: read-all
jobs:
  test_windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: windows-2025
          python-version: '3.14'
          toxenv: 'py314'
        - os: windows-2025
          python-version: '3.14'
          toxenv: 'end2end'
    steps:
    - name: Configure git
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions
    - name: Install pywin32 to ensure sys.platform is working as expected
      run: |
        python -m pip install pywin32
        python %PYTHON%\Scripts\pywin32_postinstall.py -install
    - name: Run tests
      run: |
        tox -e ${{ matrix.toxenv }}
